# Basic
title: 野渡无人舟自横
subtitle: 生活/技术
welcome_message: 
description: 愿无岁月可回首
creator: <a href="https://kuzzh.github.io">@kuzzh</a>

url: "https://kuzzh.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 游戏, description: 使用 HTML 5 写的小游戏 , url: 'https://kuzzh.github.io/2018/12/html5-game/'}
    - {title: 关于, description: 关于这个网站, url: 'https://kuzzh.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    #disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: kuzzh
    github: kuzzh
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: sarlanori@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
